### ISSUE TITLE
 android.app.RemoteServiceException: Bad notification for startForeground

### ISSUE THREAD

**Issue by MdAshraf9870** [SanjayDevTech/Screen-Recorder#3]
android.app.RemoteServiceException: Bad notification for startForeground

**Comment by ivankrylatskoe** [comment]
+1

android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by SanjayDevTech** [comment]
@ivankrylatskoe @MdAshraf9870 The issue has been solved and tested with old and new devices
