### ISSUE TITLE
Mediarecorder.stop failed

### ISSUE THREAD

**Issue by dineshchavhan** [SanjayDevTech/Screen-Recorder#6]
why mediarecorder stop has failed - 1007 error code
given all permission,

**Comment by SanjayDevTech** [comment]
> why mediarecorder stop has failed - 1007 error code
> given all permission,  

Can you share the stack trace?

**Comment by dineshchavhan** [comment]
Hi SanjayDevTech/Screen-Recorder

Please have a look below stack trace

                       Process: com.sanjay.ezyscreenrecorder, PID: 16111

                        java.lang.RuntimeException: Unable to destroy
activity
{com.sanjay.ezyscreenrecorder/com.sanjay.ezyscreenrecorder.MainActivity}:
java.lang.IllegalStateException

                        at
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)

                        at
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)

                        at android.app.ActivityThread.-wrap5(Unknown
Source:0)

                        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)

                        at
android.os.Handler.dispatchMessage(Handler.java:106)

                        at android.os.Looper.loop(Looper.java:164)

                        at
android.app.ActivityThread.main(ActivityThread.java:6494)

                        at java.lang.reflect.Method.invoke(Native Method)

                        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

                        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

                        Caused by: java.lang.IllegalStateException

                        at android.media.MediaRecorder.stop(Native Method)

                        at
com.sanjay.ezyscreenrecorder.ScreenRecorder.stop(ScreenRecorder.kt:95)

                        at
com.sanjay.ezyscreenrecorder.MainAppViewModel.stopRecording(MainAppViewModel.kt:25)

                        at
com.sanjay.ezyscreenrecorder.MainAppViewModel.onCleared(MainAppViewModel.kt:33)

                        at
androidx.lifecycle.ViewModel.clear(ViewModel.java:190)

                        at
androidx.lifecycle.ViewModelStore.clear(ViewModelStore.kt:72)

                        at
androidx.activity.ComponentActivity._init_$lambda$3(ComponentActivity.kt:271)

                        at
androidx.activity.ComponentActivity.$r8$lambda$rJQNM1M7Vkmb7bGfu3UBP50ggDI(Unknown
Source:0)

                        at
androidx.activity.ComponentActivity$$ExternalSyntheticLambda3.onStateChanged(Unknown
Source:2)

                        at
androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)

                        at
androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.kt:266)

                        at
androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:283)

                        at
androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)

                        at
androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)

                        at
androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)

                        at
androidx.lifecycle.ReportFragment.dispatch(ReportFragment.kt:87)

                        at
androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.kt:77)

                        at
android.app.Fragment.performDestroy(Fragment.java:2768)

                        at
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1432)

                        at
android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)

                        at
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)

                        at
android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)

                        at
android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3007)

                        at
android.app.FragmentController.dispatchDestroy(FragmentController.java:244)

                        at
android.app.Activity.performDestroy(Activity.java:7217)

                        at
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)

                        at
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)

                        at
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)

                        at android.app.ActivityThread.-wrap5(Unknown
Source:0)

                        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)

                        at
android.os.Handler.dispatchMessage(Handler.java:106)

                        at android.os.Looper.loop(Looper.java:164)

                        at
android.app.ActivityThread.main(ActivityThread.java:6494)

                        at java.lang.reflect.Method.invoke(Native Method)

                        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

                        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by SanjayDevTech** [comment]
I cannot fix the issue as it was tested on very old Android version . damn time goes fast
I tried to fix and made it complicated
